#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"
valid_branch_regex='^(fix|feature)\/[a-zA-Z0-9_\-]+$'
branch_error_message="Branch name should be development/master/main or in following format: feature-fix/<issue_id>_<branch description>"

if [[ $local_branch_name != 'main' && $local_branch_name != 'master' && $local_branch_name != 'development' && ! $local_branch_name =~ $valid_branch_regex ]]; then
    echo "$branch_error_message"
    exit 1
fi

commit_message="$(cat "$1")"
valid_commit_regex='^.{1,72}$'
commit_error_message="Commit message should be less than 72 symbols."

if [[ ! $commit_message =~ $valid_commit_regex ]]; then
    echo "$commit_error_message"
    exit 1
fi

exit 0
